### ISSUE TITLE
How to determine the sign of the following fomula?

### ISSUE THREAD

**Issue by songkq** [Quicksign/tfGAD#1]
Thanks for sharing the code.
I have some issues about calculating the diffused image.
A discrete numerical solution can be derived for the anisotropic case using the FTCS method as follows:
![image](https://user-images.githubusercontent.com/30183023/66488886-48b6ee00-eae1-11e9-9c44-0a597b9f26d2.png)
where {N, S, W, E} correspond to the pixel above, below, left and right of the pixel under consideration (i, j). And c is based on the gradient magnitude, thus it does not matter if we take forward or backward gradients.
How to determine the sign of diffusion coefficient item, i.e. 
```
diffused = image[:, :, 1:-1, 1:-1] + lambda_ * (
        cv[:, 1:, :] * dv[:, :, 1:, :]
        - cv[:, :-1, :] * dv[:, :, :-1, :]
        + ch[:, :, 1:] * dh[:, :, :, 1:]
        - ch[:, :, :-1] * dh[:, :, :, :-1]
    )
```
Looking forward to your reply.

**Comment by nshaud** [comment]
> How to determine the sign of diffusion coefficient item

I'm not sure I understood your question. The North and South gradients have opposite values so we compute them once and flip the sign in the summation. Is that what you're looking for?

**Comment by rcdaudt** [comment]
> > How to determine the sign of diffusion coefficient item
> 
> I'm not sure I understood your question. The North and South gradients have opposite values so we compute them once and flip the sign in the summation. Is that what you're looking for?

**nshaud** is correct. The coefficients in the equation you provided should always be positive to ensure stability. The negative terms in the code are simply a way to avoid redundant calculations.

**Comment by songkq** [comment]
@nshaud @rcdaudt Thanks for quickly reply.
